# Generated by Django 5.2.5 on 2025-08-30 21:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainnet_enabled', models.BooleanField(default=False)),
                ('autotrade_enabled', models.BooleanField(default=False)),
                ('base_currency', models.CharField(default='GBP', max_length=8)),
                ('per_trade_cap_base', models.DecimalField(decimal_places=4, default=Decimal('75'), max_digits=20)),
                ('daily_cap_base', models.DecimalField(decimal_places=4, default=Decimal('500'), max_digits=20)),
                ('hot_wallet_hard_cap_base', models.DecimalField(decimal_places=4, default=Decimal('200'), max_digits=20)),
                ('slippage_bps_new_pair', models.PositiveIntegerField(default=700)),
                ('slippage_bps_normal', models.PositiveIntegerField(default=300)),
                ('tp_percent', models.PositiveIntegerField(default=40)),
                ('sl_percent', models.PositiveIntegerField(default=20)),
                ('trailing_percent', models.PositiveIntegerField(default=15)),
                ('token_cooldown_sec', models.PositiveIntegerField(default=60)),
                ('chain_cooldown_sec', models.PositiveIntegerField(default=300)),
                ('fail_streak_pause', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Settings',
                'verbose_name_plural': 'Bot Settings',
            },
        ),
    ]
