# Generated by Django 5.2.5 on 2025-08-30 20:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=24)),
                ('network', models.CharField(blank=True, max_length=20)),
                ('dex', models.CharField(blank=True, max_length=40)),
                ('pair_address', models.CharField(blank=True, max_length=100)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('amount_in', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=38)),
                ('amount_out', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=38)),
                ('fee_native', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=38)),
                ('pnl_native', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=38)),
                ('status', models.CharField(default='ok', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=140)),
                ('trace_id', models.CharField(blank=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='storage_led_timesta_453bda_idx'), models.Index(fields=['event_type'], name='storage_led_event_t_061272_idx'), models.Index(fields=['tx_hash'], name='storage_led_tx_hash_01935a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('rpc', 'RPC'), ('aggregator', 'Aggregator'), ('security', 'Security'), ('ws', 'WebSocket'), ('other', 'Other')], default='rpc', max_length=16)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('mode', models.CharField(default='free', max_length=8)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'enabled'], name='storage_pro_kind_cfad6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=24)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('decimals', models.PositiveSmallIntegerField(default=18)),
                ('fee_on_transfer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['chain', 'symbol'], name='storage_tok_chain_c9415b_idx')],
                'unique_together': {('chain', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=20)),
                ('dex', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('fee_bps', models.PositiveIntegerField(default=0)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_pairs', to='storage.token')),
                ('quote_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_pairs', to='storage.token')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=20)),
                ('dex', models.CharField(max_length=40)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('autotrade', 'Autotrade')], default='manual', max_length=9)),
                ('amount_in', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=38)),
                ('amount_out', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=38)),
                ('exec_price', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=38)),
                ('slippage_bps', models.PositiveIntegerField(default=0)),
                ('gas_native', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=38)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='filled', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.pair')),
            ],
        ),
        migrations.AddIndex(
            model_name='pair',
            index=models.Index(fields=['chain', 'dex'], name='storage_pai_chain_78f8a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('chain', 'dex', 'address')},
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['chain', 'dex'], name='storage_tra_chain_f4da8d_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['tx_hash'], name='storage_tra_tx_hash_b66e5f_idx'),
        ),
    ]
