# Generated by Django 5.2.5 on 2025-08-31 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('total_value_usd', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_realized_pnl_usd', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_unrealized_pnl_usd', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('total_fees_paid_usd', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('win_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_paper', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(db_index=True, max_length=42)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True, unique=True)),
                ('chain', models.CharField(db_index=True, max_length=20)),
                ('dex', models.CharField(max_length=30)),
                ('token_in', models.CharField(max_length=42)),
                ('token_out', models.CharField(max_length=42)),
                ('amount_in', models.DecimalField(decimal_places=18, max_digits=36)),
                ('amount_out', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('gas_used', models.IntegerField(null=True)),
                ('gas_price_gwei', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('slippage_bps', models.IntegerField(null=True)),
                ('execution_time_ms', models.IntegerField(null=True)),
                ('is_paper', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('risk_warnings', models.JSONField(default=list)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['user_address', '-executed_at'], name='ledger_trad_user_ad_0521dd_idx'), models.Index(fields=['chain', '-executed_at'], name='ledger_trad_chain_e4ebb1_idx'), models.Index(fields=['is_paper', '-executed_at'], name='ledger_trad_is_pape_f692cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(db_index=True, max_length=42)),
                ('token_address', models.CharField(max_length=42)),
                ('chain', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('entry_price_usd', models.DecimalField(decimal_places=8, max_digits=18)),
                ('current_price_usd', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('unrealized_pnl_usd', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('realized_pnl_usd', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('is_paper', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.trade')),
            ],
            options={
                'indexes': [models.Index(fields=['user_address', 'is_active'], name='ledger_posi_user_ad_b31287_idx'), models.Index(fields=['chain', 'is_active'], name='ledger_posi_chain_cb61f9_idx')],
                'unique_together': {('user_address', 'token_address', 'chain', 'is_paper')},
            },
        ),
    ]
